### ISSUE TITLE
版本疑惑

### ISSUE THREAD

**Issue by fly0o0** [AttackXiaoJinJin/reactExplain#147]
看了官网的16.8.6版本没有ReactFiberWorkLoop.js，到16.9.0才从ReactFiberScheduler.js改成了ReactFiberWorkLoop.js，博主的版本是16.8.6吗？

**Comment by AttackXiaoJinJin** [comment]
> 看了官网的16.8.6版本没有ReactFiberWorkLoop.js，到16.9.0才从ReactFiberScheduler.js改成了ReactFiberWorkLoop.js，博主的版本是16.8.6吗？

我看了https://github.com/AttackXiaoJinJin/reactExplain/blob/master/react16.8.6/README.md，npm 上写的是 16.13.1，可能是我记错了，我把文件夹名修改下
